
alias Sync="sync ; sync ; sleep 1 ; sync; sync"
alias lx="cd /usr/src/linux-2.6.9"
alias te="lx ; cd libfbui "
alias tv="lx ; cd libfbui/Viewer "
alias mk="lx ; make "
alias fv="lx ; vi drivers/video/vesafb.c "
alias efb="lx ; vi drivers/video/fbui.c "
alias in="lx ; vi include/linux/fb.h "
alias tem="tail /var/log/messages"
alias vem="vi /var/log/messages"
alias rem="rm /var/log/messages"
alias ves="vi /var/log/syslog"
alias mm="lx ; make menuconfig"
alias pf="ps -aux"
alias ps="/usr/bin/ps aux"
alias ..="cd .."
alias fn="lx ; vi drivers/video/neofb.c "
